title: "Joe’s Cloud & DevOps Portfolio"
description: "Resilient static hosting on GitHub Pages + CloudFront + S3 failover"

# GitHub Pages–supported remote theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Make sure Jekyll processes Markdown 
markdown: kramdown

# Canonical site settings
url: "https://joesinthe.cloud"

baseurl: ""
