title: "Joe’s Cloud & DevOps Portfolio"
description: "Resilient static hosting on GitHub Pages + CloudFront + S3 failover"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Since CloudFront maps your domain to the project path, keep baseurl empty.
url: "https://joesinthe.cloud"
baseurl: ""
