name: Build & Deploy (Pages + S3 Mirror)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write   # required for OIDC

# Prevent overlapping runs from stepping on each other or double-uploading artifacts
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If you add a static site build later (Hugo/Eleventy/etc),
      # build to ./site and change the upload 'path' to 'site'.
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # change to your build output folder if you build (e.g., 'site')

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Download the same artifact so we can mirror it to S3
      - name: Download built site artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages   # default name produced by upload-pages-artifact
          path: site           # will contain the rendered site

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::949367020370:role/mywebsite-roles
          aws-region: us-east-1

      - name: Mirror site to S3 (failover origin)
        run: aws s3 sync "site/" "s3://joesinthecloud-mirror/" --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ENRUG2COZMRM7 --paths "/*"
